[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.95", default-features = false }
bincode = "1.3.3"
serde = { version = "1.0.217", default-features = false, features = [
	"serde_derive",
] }
